version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
    networks:
      - xnet

  myapp:
    build: .
    image: sevim/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - xnet

networks:
  xnet:
    driver: bridge
